networks:
  caddy:
    external: true

services:
  starlinkdash:
    image: ghcr.io/lstepnio/starlinkdash:latest
    pull_policy: always
    container_name: starlinkdash
    restart: unless-stopped
    networks:
      - caddy
    env_file: .env
    volumes:
      - /docker/appdata/starlinkdash:/data
    environment:
      DB_PATH: /data/starlinkdash.db
    labels:
      caddy: dash.majjix.com
      caddy.reverse_proxy: "{{upstreams 8000}}"
